# -*- coding: utf-8 -*-
"""Tratamento_inserção_dados_em_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13O2LFDy7LXKqSbabHVRBPJDfDjV4TXP1
"""

from modules.postgres import Conector_postgres
import pandas as pd
from tqdm import tqdm
from time import sleep

'''
Função criada para leitura e tratamento de arquivos csv, contendo uma barra de progresso que informa o usuário,
quantos registros ele irá inserir e o tempo restante para a conclusão da inserção no banco de dados, 
trazendo os dados inseridos na tabela.

By: Ricardo Alex de Lima

'''

if __name__ =="__main__":

    try:
        def leitura_e_tratamento():
            #trazendo o conector
            banco = Conector_postgres(host="127.0.0.1", db="ATV14")
            #lendo o arquivo csv
            df = pd.read_csv(input('Digite o caminho do arquivo: '))
            
            #tratando todos os campos em branco
            dados = df.dropna(how="any", axis=0)
            
            #adicionando a barra de progresso que mostra a quantidade de registros, pegando pelo índice, 
            # junto com tempo que falta para a conclusão da inserção.
            with tqdm(total=df.shape[0]) as pbar: 
                #percorrendo o csv tratado e inserindo no banco
                for index, row in dados.iterrows():
                    pbar.update(1)
                    banco.inserir(f"INSERT INTO aula_csv (datas, valor) VALUES ('{row['data']}', '{row['valor']}'); ")   
                    sleep(0.25)
                #retorno do for
                print('Os registros inseridos com sucesso!\n')
                print('\n')
            #fazendo uma nova query
            df = pd.DataFrame(banco.selecionar(f"SELECT * FROM aula_csv"))
            #retorno da query
            print(df)
        #fim da função
        leitura_e_tratamento()
        
    except Exception as e :
        print(str(e))